Pipeline

diff --git a/.github/workflows/local_deployment_pipeline.yml b/.github/workflows/local_deployment_pipeline.yml
--- a/.github/workflows/local_deployment_pipeline.yml
+++ b/.github/workflows/local_deployment_pipeline.yml
@@ -30,7 +30,8 @@ jobs:
       open /Applications/Docker.app
     - name: Wait for Docker to start
       run: |
-        for ((i = 0; i <30; i++)); do docker ps &> /dev/null && break || echo "Docker is not open yet. Retrying in 1 second..."; sleep 1; done
+        sleep 30
+        # for ((i = 0; i <30; i++)); do docker ps &> /dev/null && break || echo "Docker is not open yet. Retrying in 1 second..."; sleep 1; done
     - name: Initialize environment
       run: |
         make init-env
